services:
  - type: web
    env: node
    name: cloudnest-ai-backend
    buildCommand: chmod +x build-verify.sh && ./build-verify.sh
    startCommand: node server.js
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          property: port
